package word2number

import "testing"

var (
	mapNumbers = map[int]string{
		1:    "Uno",
		2:    "Dos",
		3:    "Tres",
		4:    "Cuatro",
		5:    "Cinco",
		6:    "Seis",
		7:    "Siete",
		8:    "Ocho",
		9:    "Nueve",
		10:   "Diez",
		11:   "Once",
		12:   "Doce",
		13:   "Trece",
		14:   "Catorce",
		15:   "Quince",
		16:   "Dieciséis",
		17:   "Diecisiete",
		18:   "Dieciocho",
		19:   "Diecinueve",
		20:   "Veinte",
		21:   "Veintiuno",
		22:   "Veintidos",
		23:   "Veintitres",
		24:   "Veinticuatro",
		25:   "Veinticinco",
		26:   "Veintiseis",
		27:   "Veintisiete",
		28:   "Veintiocho",
		29:   "Veintinueve",
		30:   "Treinta",
		31:   "Treinta y uno",
		32:   "Treinta y dos",
		33:   "Treinta y tres",
		34:   "Treinta y cuatro",
		35:   "Treinta y cinco",
		36:   "Treinta y seis",
		37:   "Treinta y siete",
		38:   "Treinta y ocho",
		39:   "Treinta y nueve",
		40:   "Cuarenta",
		41:   "Cuarenta y uno",
		42:   "Cuarenta y dos",
		43:   "Cuarenta y tres",
		44:   "Cuarenta y cuatro",
		45:   "Cuarenta y cinco",
		46:   "Cuarenta y seis",
		47:   "Cuarenta y siete",
		48:   "Cuarenta y ocho",
		49:   "Cuarenta y nueve",
		50:   "Cincuenta",
		51:   "Cincuenta y uno",
		52:   "Cincuenta y dos",
		53:   "Cincuenta y tres",
		54:   "Cincuenta y cuatro",
		55:   "Cincuenta y cinco",
		56:   "Cincuenta y seis",
		57:   "Cincuenta y siete",
		58:   "Cincuenta y ocho",
		59:   "Cincuenta y nueve",
		60:   "Sesenta",
		61:   "Sesenta y uno",
		62:   "Sesenta y dos",
		63:   "Sesenta y tres",
		64:   "Sesenta y cuatro",
		65:   "Sesenta y cinco",
		66:   "Sesenta y seis",
		67:   "Sesenta y siete",
		68:   "Sesenta y ocho",
		69:   "Sesenta y nueve",
		70:   "Setenta",
		71:   "Setenta y uno",
		72:   "Setenta y dos",
		73:   "Setenta y tres",
		74:   "Setenta y cuatro",
		75:   "Setenta y cinco",
		76:   "Setenta y seis",
		77:   "Setenta y siete",
		78:   "Setenta y ocho",
		79:   "Setenta y nueve",
		80:   "Ochenta",
		81:   "Ochenta y uno",
		82:   "Ochenta y dos",
		83:   "Ochenta y tres",
		84:   "Ochenta y cuatro",
		85:   "Ochenta y cinco",
		86:   "Ochenta y seis",
		87:   "Ochenta y siete",
		88:   "Ochenta y ocho",
		89:   "Ochenta y nueve",
		90:   "Noventa",
		91:   "Noventa y uno",
		92:   "Noventa y dos",
		93:   "Noventa y tres",
		94:   "Noventa y cuatro",
		95:   "Noventa y cinco",
		96:   "Noventa y seis",
		97:   "Noventa y siete",
		98:   "Noventa y ocho",
		99:   "Noventa y nueve",
		100:  "Cien",
		101:  "Ciento uno",
		102:  "Ciento dos",
		103:  "Ciento tres",
		104:  "Ciento cuatro",
		105:  "Ciento cinco",
		106:  "Ciento seis",
		107:  "Ciento siete",
		108:  "Ciento ocho",
		109:  "Ciento nueve",
		110:  "Ciento diez",
		111:  "Ciento once",
		112:  "Ciento doce",
		113:  "Ciento trece",
		114:  "Ciento catorce",
		115:  "Ciento quince",
		116:  "Ciento dieciséis",
		117:  "Ciento diecisiete",
		118:  "Ciento dieciocho",
		119:  "Ciento diecinueve",
		120:  "Ciento veinte",
		121:  "Ciento veintiuno",
		122:  "Ciento veintidos",
		123:  "Ciento veintitrés",
		124:  "Ciento veinticuatro",
		125:  "Ciento veinticinco",
		126:  "Ciento veintiseis",
		127:  "Ciento veintisiete",
		128:  "Ciento veintiocho",
		129:  "Ciento veintinueve",
		130:  "Ciento treinta",
		131:  "Ciento treinta y uno",
		132:  "Ciento treinta y dos",
		133:  "Ciento treinta y tres",
		134:  "Ciento treinta y cuatro",
		135:  "Ciento treinta y cinco",
		136:  "Ciento treinta y seis",
		137:  "Ciento treinta y siete",
		138:  "Ciento treinta y ocho",
		139:  "Ciento treinta y nueve",
		140:  "Ciento cuarenta",
		141:  "Ciento cuarenta y uno",
		142:  "Ciento cuarenta y dos",
		143:  "Ciento cuarenta y tres",
		144:  "Ciento cuarenta y cuatro",
		145:  "Ciento cuarenta y cinco",
		146:  "Ciento cuarenta y seis",
		147:  "Ciento cuarenta y siete",
		148:  "Ciento cuarenta y ocho",
		149:  "Ciento cuarenta y nueve",
		150:  "Ciento cincuenta",
		151:  "Ciento cincuenta y uno",
		152:  "Ciento cincuenta y dos",
		153:  "Ciento cincuenta y tres",
		154:  "Ciento cincuenta y cuatro",
		155:  "Ciento cincuenta y cinco",
		156:  "Ciento cincuenta y seis",
		157:  "Ciento cincuenta y siete",
		158:  "Ciento cincuenta y ocho",
		159:  "Ciento cincuenta y nueve",
		160:  "Ciento sesenta",
		161:  "Ciento sesenta y uno",
		162:  "Ciento sesenta y dos",
		163:  "Ciento sesenta y tres",
		164:  "Ciento sesenta y cuatro",
		165:  "Ciento sesenta y cinco",
		166:  "Ciento sesenta y seis",
		167:  "Ciento sesenta y siete",
		168:  "Ciento sesenta y ocho",
		169:  "Ciento sesenta y nueve",
		170:  "Ciento setenta",
		171:  "Ciento setenta y uno",
		172:  "Ciento setenta y dos",
		173:  "Ciento setenta y tres",
		174:  "Ciento setenta y cuatro",
		175:  "Ciento setenta y cinco",
		176:  "Ciento setenta y seis",
		177:  "Ciento setenta y siete",
		178:  "Ciento setenta y ocho",
		179:  "Ciento setenta y nueve",
		180:  "Ciento ochenta",
		181:  "Ciento ochenta y uno",
		182:  "Ciento ochenta y dos",
		183:  "Ciento ochenta y tres",
		184:  "Ciento ochenta y cuatro",
		185:  "Ciento ochenta y cinco",
		186:  "Ciento ochenta y seis",
		187:  "Ciento ochenta y siete",
		188:  "Ciento ochenta y ocho",
		189:  "Ciento ochenta y nueve",
		190:  "Ciento noventa",
		191:  "Ciento noventa y uno",
		192:  "Ciento noventa y dos",
		193:  "Ciento noventa y tres",
		194:  "Ciento noventa y cuatro",
		195:  "Ciento noventa y cinco",
		196:  "Ciento noventa y seis",
		197:  "Ciento noventa y siete",
		198:  "Ciento noventa y ocho",
		199:  "Ciento noventa y nueve",
		200:  "Doscientos",
		201:  "Doscientos uno",
		202:  "Doscientos dos",
		203:  "Doscientos tres",
		204:  "Doscientos cuatro",
		205:  "Doscientos cinco",
		206:  "Doscientos seis",
		207:  "Doscientos siete",
		208:  "Doscientos ocho",
		209:  "Doscientos nueve",
		210:  "Doscientos diez",
		211:  "Doscientos once",
		212:  "Doscientos doce",
		213:  "Doscientos trece",
		214:  "Doscientos catorce",
		215:  "Doscientos quince",
		216:  "Doscientos dieciséis",
		217:  "Doscientos diecisiete",
		218:  "Doscientos dieciocho",
		219:  "Doscientos diecinueve",
		220:  "Doscientos veinte",
		221:  "Doscientos veintiuno",
		222:  "Doscientos veintidos",
		223:  "Doscientos veintitrés",
		224:  "Doscientos veinticuatro",
		225:  "Doscientos veinticinco",
		226:  "Doscientos veintiseis",
		227:  "Doscientos veintisiete",
		228:  "Doscientos veintiocho",
		229:  "Doscientos veintinueve",
		230:  "Doscientos treinta",
		231:  "Doscientos treinta y uno",
		232:  "Doscientos treinta y dos",
		233:  "Doscientos treinta y tres",
		234:  "Doscientos treinta y cuatro",
		235:  "Doscientos treinta y cinco",
		236:  "Doscientos treinta y seis",
		237:  "Doscientos treinta y siete",
		238:  "Doscientos treinta y ocho",
		239:  "Doscientos treinta y nueve",
		240:  "Doscientos cuarenta",
		241:  "Doscientos cuarenta y uno",
		242:  "Doscientos cuarenta y dos",
		243:  "Doscientos cuarenta y tres",
		244:  "Doscientos cuarenta y cuatro",
		245:  "Doscientos cuarenta y cinco",
		246:  "Doscientos cuarenta y seis",
		247:  "Doscientos cuarenta y siete",
		248:  "Doscientos cuarenta y ocho",
		249:  "Doscientos cuarenta y nueve",
		250:  "Doscientos cincuenta",
		251:  "Doscientos cincuenta y uno",
		252:  "Doscientos cincuenta y dos",
		253:  "Doscientos cincuenta y tres",
		254:  "Doscientos cincuenta y cuatro",
		255:  "Doscientos cincuenta y cinco",
		256:  "Doscientos cincuenta y seis",
		257:  "Doscientos cincuenta y siete",
		258:  "Doscientos cincuenta y ocho",
		259:  "Doscientos cincuenta y nueve",
		260:  "Doscientos sesenta",
		261:  "Doscientos sesenta y uno",
		262:  "Doscientos sesenta y dos",
		263:  "Doscientos sesenta y tres",
		264:  "Doscientos sesenta y cuatro",
		265:  "Doscientos sesenta y cinco",
		266:  "Doscientos sesenta y seis",
		267:  "Doscientos sesenta y siete",
		268:  "Doscientos sesenta y ocho",
		269:  "Doscientos sesenta y nueve",
		270:  "Doscientos setenta",
		271:  "Doscientos setenta y uno",
		272:  "Doscientos setenta y dos",
		273:  "Doscientos setenta y tres",
		274:  "Doscientos setenta y cuatro",
		275:  "Doscientos setenta y cinco",
		276:  "Doscientos setenta y seis",
		277:  "Doscientos setenta y siete",
		278:  "Doscientos setenta y ocho",
		279:  "Doscientos setenta y nueve",
		280:  "Doscientos ochenta",
		281:  "Doscientos ochenta y uno",
		282:  "Doscientos ochenta y dos",
		283:  "Doscientos ochenta y tres",
		284:  "Doscientos ochenta y cuatro",
		285:  "Doscientos ochenta y cinco",
		286:  "Doscientos ochenta y seis",
		287:  "Doscientos ochenta y siete",
		288:  "Doscientos ochenta y ocho",
		289:  "Doscientos ochenta y nueve",
		290:  "Doscientos noventa",
		291:  "Doscientos noventa y uno",
		292:  "Doscientos noventa y dos",
		293:  "Doscientos noventa y tres",
		294:  "Doscientos noventa y cuatro",
		295:  "Doscientos noventa y cinco",
		296:  "Doscientos noventa y seis",
		297:  "Doscientos noventa y siete",
		298:  "Doscientos noventa y ocho",
		299:  "Doscientos noventa y nueve",
		300:  "Trescientos",
		301:  "Trescientos uno",
		302:  "Trescientos dos",
		303:  "Trescientos tres",
		304:  "Trescientos cuatro",
		305:  "Trescientos cinco",
		306:  "Trescientos seis",
		307:  "Trescientos siete",
		308:  "Trescientos ocho",
		309:  "Trescientos nueve",
		310:  "Trescientos diez",
		311:  "Trescientos once",
		312:  "Trescientos doce",
		313:  "Trescientos trece",
		314:  "Trescientos catorce",
		315:  "Trescientos quince",
		316:  "Trescientos dieciséis",
		317:  "Trescientos diecisiete",
		318:  "Trescientos dieciocho",
		319:  "Trescientos diecinueve",
		320:  "Trescientos veinte",
		321:  "Trescientos veintiuno",
		322:  "Trescientos veintidos",
		323:  "Trescientos veintitrés",
		324:  "Trescientos veinticuatro",
		325:  "Trescientos veinticinco",
		326:  "Trescientos veintiseis",
		327:  "Trescientos veintisiete",
		328:  "Trescientos veintiocho",
		329:  "Trescientos veintinueve",
		330:  "Trescientos treinta",
		331:  "Trescientos treinta y uno",
		332:  "Trescientos treinta y dos",
		333:  "Trescientos treinta y tres",
		334:  "Trescientos treinta y cuatro",
		335:  "Trescientos treinta y cinco",
		336:  "Trescientos treinta y seis",
		337:  "Trescientos treinta y siete",
		338:  "Trescientos treinta y ocho",
		339:  "Trescientos treinta y nueve",
		340:  "Trescientos cuarenta",
		341:  "Trescientos cuarenta y uno",
		342:  "Trescientos cuarenta y dos",
		343:  "Trescientos cuarenta y tres",
		344:  "Trescientos cuarenta y cuatro",
		345:  "Trescientos cuarenta y cinco",
		346:  "Trescientos cuarenta y seis",
		347:  "Trescientos cuarenta y siete",
		348:  "Trescientos cuarenta y ocho",
		349:  "Trescientos cuarenta y nueve",
		350:  "Trescientos cincuenta",
		351:  "Trescientos cincuenta y uno",
		352:  "Trescientos cincuenta y dos",
		353:  "Trescientos cincuenta y tres",
		354:  "Trescientos cincuenta y cuatro",
		355:  "Trescientos cincuenta y cinco",
		356:  "Trescientos cincuenta y seis",
		357:  "Trescientos cincuenta y siete",
		358:  "Trescientos cincuenta y ocho",
		359:  "Trescientos cincuenta y nueve",
		360:  "Trescientos sesenta",
		361:  "Trescientos sesenta y uno",
		362:  "Trescientos sesenta y dos",
		363:  "Trescientos sesenta y tres",
		364:  "Trescientos sesenta y cuatro",
		365:  "Trescientos sesenta y cinco",
		366:  "Trescientos sesenta y seis",
		367:  "Trescientos sesenta y siete",
		368:  "Trescientos sesenta y ocho",
		369:  "Trescientos sesenta y nueve",
		370:  "Trescientos setenta",
		371:  "Trescientos setenta y uno",
		372:  "Trescientos setenta y dos",
		373:  "Trescientos setenta y tres",
		374:  "Trescientos setenta y cuatro",
		375:  "Trescientos setenta y cinco",
		376:  "Trescientos setenta y seis",
		377:  "Trescientos setenta y siete",
		378:  "Trescientos setenta y ocho",
		379:  "Trescientos setenta y nueve",
		380:  "Trescientos ochenta",
		381:  "Trescientos ochenta y uno",
		382:  "Trescientos ochenta y dos",
		383:  "Trescientos ochenta y tres",
		384:  "Trescientos ochenta y cuatro",
		385:  "Trescientos ochenta y cinco",
		386:  "Trescientos ochenta y seis",
		387:  "Trescientos ochenta y siete",
		388:  "Trescientos ochenta y ocho",
		389:  "Trescientos ochenta y nueve",
		390:  "Trescientos noventa",
		391:  "Trescientos noventa y uno",
		392:  "Trescientos noventa y dos",
		393:  "Trescientos noventa y tres",
		394:  "Trescientos noventa y cuatro",
		395:  "Trescientos noventa y cinco",
		396:  "Trescientos noventa y seis",
		397:  "Trescientos noventa y siete",
		398:  "Trescientos noventa y ocho",
		399:  "Trescientos noventa y nueve",
		400:  "Cuatrocientos",
		401:  "Cuatrocientos uno",
		402:  "Cuatrocientos dos",
		403:  "Cuatrocientos tres",
		404:  "Cuatrocientos cuatro",
		405:  "Cuatrocientos cinco",
		406:  "Cuatrocientos seis",
		407:  "Cuatrocientos siete",
		408:  "Cuatrocientos ocho",
		409:  "Cuatrocientos nueve",
		410:  "Cuatrocientos diez",
		411:  "Cuatrocientos once",
		412:  "Cuatrocientos doce",
		413:  "Cuatrocientos trece",
		414:  "Cuatrocientos catorce",
		415:  "Cuatrocientos quince",
		416:  "Cuatrocientos dieciséis",
		417:  "Cuatrocientos diecisiete",
		418:  "Cuatrocientos dieciocho",
		419:  "Cuatrocientos diecinueve",
		420:  "Cuatrocientos veinte",
		421:  "Cuatrocientos veintiuno",
		422:  "Cuatrocientos veintidos",
		423:  "Cuatrocientos veintitrés",
		424:  "Cuatrocientos veinticuatro",
		425:  "Cuatrocientos veinticinco",
		426:  "Cuatrocientos veintiseis",
		427:  "Cuatrocientos veintisiete",
		428:  "Cuatrocientos veintiocho",
		429:  "Cuatrocientos veintinueve",
		430:  "Cuatrocientos treinta",
		431:  "Cuatrocientos treinta y uno",
		432:  "Cuatrocientos treinta y dos",
		433:  "Cuatrocientos treinta y tres",
		434:  "Cuatrocientos treinta y cuatro",
		435:  "Cuatrocientos treinta y cinco",
		436:  "Cuatrocientos treinta y seis",
		437:  "Cuatrocientos treinta y siete",
		438:  "Cuatrocientos treinta y ocho",
		439:  "Cuatrocientos treinta y nueve",
		440:  "Cuatrocientos cuarenta",
		441:  "Cuatrocientos cuarenta y uno",
		442:  "Cuatrocientos cuarenta y dos",
		443:  "Cuatrocientos cuarenta y tres",
		444:  "Cuatrocientos cuarenta y cuatro",
		445:  "Cuatrocientos cuarenta y cinco",
		446:  "Cuatrocientos cuarenta y seis",
		447:  "Cuatrocientos cuarenta y siete",
		448:  "Cuatrocientos cuarenta y ocho",
		449:  "Cuatrocientos cuarenta y nueve",
		450:  "Cuatrocientos cincuenta",
		451:  "Cuatrocientos cincuenta y uno",
		452:  "Cuatrocientos cincuenta y dos",
		453:  "Cuatrocientos cincuenta y tres",
		454:  "Cuatrocientos cincuenta y cuatro",
		455:  "Cuatrocientos cincuenta y cinco",
		456:  "Cuatrocientos cincuenta y seis",
		457:  "Cuatrocientos cincuenta y siete",
		458:  "Cuatrocientos cincuenta y ocho",
		459:  "Cuatrocientos cincuenta y nueve",
		460:  "Cuatrocientos sesenta",
		461:  "Cuatrocientos sesenta y uno",
		462:  "Cuatrocientos sesenta y dos",
		463:  "Cuatrocientos sesenta y tres",
		464:  "Cuatrocientos sesenta y cuatro",
		465:  "Cuatrocientos sesenta y cinco",
		466:  "Cuatrocientos sesenta y seis",
		467:  "Cuatrocientos sesenta y siete",
		468:  "Cuatrocientos sesenta y ocho",
		469:  "Cuatrocientos sesenta y nueve",
		470:  "Cuatrocientos setenta",
		471:  "Cuatrocientos setenta y uno",
		472:  "Cuatrocientos setenta y dos",
		473:  "Cuatrocientos setenta y tres",
		474:  "Cuatrocientos setenta y cuatro",
		475:  "Cuatrocientos setenta y cinco",
		476:  "Cuatrocientos setenta y seis",
		477:  "Cuatrocientos setenta y siete",
		478:  "Cuatrocientos setenta y ocho",
		479:  "Cuatrocientos setenta y nueve",
		480:  "Cuatrocientos ochenta",
		481:  "Cuatrocientos ochenta y uno",
		482:  "Cuatrocientos ochenta y dos",
		483:  "Cuatrocientos ochenta y tres",
		484:  "Cuatrocientos ochenta y cuatro",
		485:  "Cuatrocientos ochenta y cinco",
		486:  "Cuatrocientos ochenta y seis",
		487:  "Cuatrocientos ochenta y siete",
		488:  "Cuatrocientos ochenta y ocho",
		489:  "Cuatrocientos ochenta y nueve",
		490:  "Cuatrocientos noventa",
		491:  "Cuatrocientos noventa y uno",
		492:  "Cuatrocientos noventa y dos",
		493:  "Cuatrocientos noventa y tres",
		494:  "Cuatrocientos noventa y cuatro",
		495:  "Cuatrocientos noventa y cinco",
		496:  "Cuatrocientos noventa y seis",
		497:  "Cuatrocientos noventa y siete",
		498:  "Cuatrocientos noventa y ocho",
		499:  "Cuatrocientos noventa y nueve",
		500:  "Quinientos",
		501:  "Quinientos uno",
		502:  "Quinientos dos",
		503:  "Quinientos tres",
		504:  "Quinientos cuatro",
		505:  "Quinientos cinco",
		506:  "Quinientos seis",
		507:  "Quinientos siete",
		508:  "Quinientos ocho",
		509:  "Quinientos nueve",
		510:  "Quinientos diez",
		511:  "Quinientos once",
		512:  "Quinientos doce",
		513:  "Quinientos trece",
		514:  "Quinientos catorce",
		515:  "Quinientos quince",
		516:  "Quinientos dieciséis",
		517:  "Quinientos diecisiete",
		518:  "Quinientos dieciocho",
		519:  "Quinientos diecinueve",
		520:  "Quinientos veinte",
		521:  "Quinientos veintiuno",
		522:  "Quinientos veintidos",
		523:  "Quinientos veintitrés",
		524:  "Quinientos veinticuatro",
		525:  "Quinientos veinticinco",
		526:  "Quinientos veintiseis",
		527:  "Quinientos veintisiete",
		528:  "Quinientos veintiocho",
		529:  "Quinientos veintinueve",
		530:  "Quinientos treinta",
		531:  "Quinientos treinta y uno",
		532:  "Quinientos treinta y dos",
		533:  "Quinientos treinta y tres",
		534:  "Quinientos treinta y cuatro",
		535:  "Quinientos treinta y cinco",
		536:  "Quinientos treinta y seis",
		537:  "Quinientos treinta y siete",
		538:  "Quinientos treinta y ocho",
		539:  "Quinientos treinta y nueve",
		540:  "Quinientos cuarenta",
		541:  "Quinientos cuarenta y uno",
		542:  "Quinientos cuarenta y dos",
		543:  "Quinientos cuarenta y tres",
		544:  "Quinientos cuarenta y cuatro",
		545:  "Quinientos cuarenta y cinco",
		546:  "Quinientos cuarenta y seis",
		547:  "Quinientos cuarenta y siete",
		548:  "Quinientos cuarenta y ocho",
		549:  "Quinientos cuarenta y nueve",
		550:  "Quinientos cincuenta",
		551:  "Quinientos cincuenta y uno",
		552:  "Quinientos cincuenta y dos",
		553:  "Quinientos cincuenta y tres",
		554:  "Quinientos cincuenta y cuatro",
		555:  "Quinientos cincuenta y cinco",
		556:  "Quinientos cincuenta y seis",
		557:  "Quinientos cincuenta y siete",
		558:  "Quinientos cincuenta y ocho",
		559:  "Quinientos cincuenta y nueve",
		560:  "Quinientos sesenta",
		561:  "Quinientos sesenta y uno",
		562:  "Quinientos sesenta y dos",
		563:  "Quinientos sesenta y tres",
		564:  "Quinientos sesenta y cuatro",
		565:  "Quinientos sesenta y cinco",
		566:  "Quinientos sesenta y seis",
		567:  "Quinientos sesenta y siete",
		568:  "Quinientos sesenta y ocho",
		569:  "Quinientos sesenta y nueve",
		570:  "Quinientos setenta",
		571:  "Quinientos setenta y uno",
		572:  "Quinientos setenta y dos",
		573:  "Quinientos setenta y tres",
		574:  "Quinientos setenta y cuatro",
		575:  "Quinientos setenta y cinco",
		576:  "Quinientos setenta y seis",
		577:  "Quinientos setenta y siete",
		578:  "Quinientos setenta y ocho",
		579:  "Quinientos setenta y nueve",
		580:  "Quinientos ochenta",
		581:  "Quinientos ochenta y uno",
		582:  "Quinientos ochenta y dos",
		583:  "Quinientos ochenta y tres",
		584:  "Quinientos ochenta y cuatro",
		585:  "Quinientos ochenta y cinco",
		586:  "Quinientos ochenta y seis",
		587:  "Quinientos ochenta y siete",
		588:  "Quinientos ochenta y ocho",
		589:  "Quinientos ochenta y nueve",
		590:  "Quinientos noventa",
		591:  "Quinientos noventa y uno",
		592:  "Quinientos noventa y dos",
		593:  "Quinientos noventa y tres",
		594:  "Quinientos noventa y cuatro",
		595:  "Quinientos noventa y cinco",
		596:  "Quinientos noventa y seis",
		597:  "Quinientos noventa y siete",
		598:  "Quinientos noventa y ocho",
		599:  "Quinientos noventa y nueve",
		600:  "Seiscientos",
		601:  "Seiscientos uno",
		602:  "Seiscientos dos",
		603:  "Seiscientos tres",
		604:  "Seiscientos cuatro",
		605:  "Seiscientos cinco",
		606:  "Seiscientos seis",
		607:  "Seiscientos siete",
		608:  "Seiscientos ocho",
		609:  "Seiscientos nueve",
		610:  "Seiscientos diez",
		611:  "Seiscientos once",
		612:  "Seiscientos doce",
		613:  "Seiscientos trece",
		614:  "Seiscientos catorce",
		615:  "Seiscientos quince",
		616:  "Seiscientos dieciséis",
		617:  "Seiscientos diecisiete",
		618:  "Seiscientos dieciocho",
		619:  "Seiscientos diecinueve",
		620:  "Seiscientos veinte",
		621:  "Seiscientos veintiuno",
		622:  "Seiscientos veintidos",
		623:  "Seiscientos veintitrés",
		624:  "Seiscientos veinticuatro",
		625:  "Seiscientos veinticinco",
		626:  "Seiscientos veintiseis",
		627:  "Seiscientos veintisiete",
		628:  "Seiscientos veintiocho",
		629:  "Seiscientos veintinueve",
		630:  "Seiscientos treinta",
		631:  "Seiscientos treinta y uno",
		632:  "Seiscientos treinta y dos",
		633:  "Seiscientos treinta y tres",
		634:  "Seiscientos treinta y cuatro",
		635:  "Seiscientos treinta y cinco",
		636:  "Seiscientos treinta y seis",
		637:  "Seiscientos treinta y siete",
		638:  "Seiscientos treinta y ocho",
		639:  "Seiscientos treinta y nueve",
		640:  "Seiscientos cuarenta",
		641:  "Seiscientos cuarenta y uno",
		642:  "Seiscientos cuarenta y dos",
		643:  "Seiscientos cuarenta y tres",
		644:  "Seiscientos cuarenta y cuatro",
		645:  "Seiscientos cuarenta y cinco",
		646:  "Seiscientos cuarenta y seis",
		647:  "Seiscientos cuarenta y siete",
		648:  "Seiscientos cuarenta y ocho",
		649:  "Seiscientos cuarenta y nueve",
		650:  "Seiscientos cincuenta",
		651:  "Seiscientos cincuenta y uno",
		652:  "Seiscientos cincuenta y dos",
		653:  "Seiscientos cincuenta y tres",
		654:  "Seiscientos cincuenta y cuatro",
		655:  "Seiscientos cincuenta y cinco",
		656:  "Seiscientos cincuenta y seis",
		657:  "Seiscientos cincuenta y siete",
		658:  "Seiscientos cincuenta y ocho",
		659:  "Seiscientos cincuenta y nueve",
		660:  "Seiscientos sesenta",
		661:  "Seiscientos sesenta y uno",
		662:  "Seiscientos sesenta y dos",
		663:  "Seiscientos sesenta y tres",
		664:  "Seiscientos sesenta y cuatro",
		665:  "Seiscientos sesenta y cinco",
		666:  "Seiscientos sesenta y seis",
		667:  "Seiscientos sesenta y siete",
		668:  "Seiscientos sesenta y ocho",
		669:  "Seiscientos sesenta y nueve",
		670:  "Seiscientos setenta",
		671:  "Seiscientos setenta y uno",
		672:  "Seiscientos setenta y dos",
		673:  "Seiscientos setenta y tres",
		674:  "Seiscientos setenta y cuatro",
		675:  "Seiscientos setenta y cinco",
		676:  "Seiscientos setenta y seis",
		677:  "Seiscientos setenta y siete",
		678:  "Seiscientos setenta y ocho",
		679:  "Seiscientos setenta y nueve",
		680:  "Seiscientos ochenta",
		681:  "Seiscientos ochenta y uno",
		682:  "Seiscientos ochenta y dos",
		683:  "Seiscientos ochenta y tres",
		684:  "Seiscientos ochenta y cuatro",
		685:  "Seiscientos ochenta y cinco",
		686:  "Seiscientos ochenta y seis",
		687:  "Seiscientos ochenta y siete",
		688:  "Seiscientos ochenta y ocho",
		689:  "Seiscientos ochenta y nueve",
		690:  "Seiscientos noventa",
		691:  "Seiscientos noventa y uno",
		692:  "Seiscientos noventa y dos",
		693:  "Seiscientos noventa y tres",
		694:  "Seiscientos noventa y cuatro",
		695:  "Seiscientos noventa y cinco",
		696:  "Seiscientos noventa y seis",
		697:  "Seiscientos noventa y siete",
		698:  "Seiscientos noventa y ocho",
		699:  "Seiscientos noventa y nueve",
		700:  "Setecientos",
		701:  "Setecientos uno",
		702:  "Setecientos dos",
		703:  "Setecientos tres",
		704:  "Setecientos cuatro",
		705:  "Setecientos cinco",
		706:  "Setecientos seis",
		707:  "Setecientos siete",
		708:  "Setecientos ocho",
		709:  "Setecientos nueve",
		710:  "Setecientos diez",
		711:  "Setecientos once",
		712:  "Setecientos doce",
		713:  "Setecientos trece",
		714:  "Setecientos catorce",
		715:  "Setecientos quince",
		716:  "Setecientos dieciséis",
		717:  "Setecientos diecisiete",
		718:  "Setecientos dieciocho",
		719:  "Setecientos diecinueve",
		720:  "Setecientos veinte",
		721:  "Setecientos veintiuno",
		722:  "Setecientos veintidos",
		723:  "Setecientos veintitrés",
		724:  "Setecientos veinticuatro",
		725:  "Setecientos veinticinco",
		726:  "Setecientos veintiseis",
		727:  "Setecientos veintisiete",
		728:  "Setecientos veintiocho",
		729:  "Setecientos veintinueve",
		730:  "Setecientos treinta",
		731:  "Setecientos treinta y uno",
		732:  "Setecientos treinta y dos",
		733:  "Setecientos treinta y tres",
		734:  "Setecientos treinta y cuatro",
		735:  "Setecientos treinta y cinco",
		736:  "Setecientos treinta y seis",
		737:  "Setecientos treinta y siete",
		738:  "Setecientos treinta y ocho",
		739:  "Setecientos treinta y nueve",
		740:  "Setecientos cuarenta",
		741:  "Setecientos cuarenta y uno",
		742:  "Setecientos cuarenta y dos",
		743:  "Setecientos cuarenta y tres",
		744:  "Setecientos cuarenta y cuatro",
		745:  "Setecientos cuarenta y cinco",
		746:  "Setecientos cuarenta y seis",
		747:  "Setecientos cuarenta y siete",
		748:  "Setecientos cuarenta y ocho",
		749:  "Setecientos cuarenta y nueve",
		750:  "Setecientos cincuenta",
		751:  "Setecientos cincuenta y uno",
		752:  "Setecientos cincuenta y dos",
		753:  "Setecientos cincuenta y tres",
		754:  "Setecientos cincuenta y cuatro",
		755:  "Setecientos cincuenta y cinco",
		756:  "Setecientos cincuenta y seis",
		757:  "Setecientos cincuenta y siete",
		758:  "Setecientos cincuenta y ocho",
		759:  "Setecientos cincuenta y nueve",
		760:  "Setecientos sesenta",
		761:  "Setecientos sesenta y uno",
		762:  "Setecientos sesenta y dos",
		763:  "Setecientos sesenta y tres",
		764:  "Setecientos sesenta y cuatro",
		765:  "Setecientos sesenta y cinco",
		766:  "Setecientos sesenta y seis",
		767:  "Setecientos sesenta y siete",
		768:  "Setecientos sesenta y ocho",
		769:  "Setecientos sesenta y nueve",
		770:  "Setecientos setenta",
		771:  "Setecientos setenta y uno",
		772:  "Setecientos setenta y dos",
		773:  "Setecientos setenta y tres",
		774:  "Setecientos setenta y cuatro",
		775:  "Setecientos setenta y cinco",
		776:  "Setecientos setenta y seis",
		777:  "Setecientos setenta y siete",
		778:  "Setecientos setenta y ocho",
		779:  "Setecientos setenta y nueve",
		780:  "Setecientos ochenta",
		781:  "Setecientos ochenta y uno",
		782:  "Setecientos ochenta y dos",
		783:  "Setecientos ochenta y tres",
		784:  "Setecientos ochenta y cuatro",
		785:  "Setecientos ochenta y cinco",
		786:  "Setecientos ochenta y seis",
		787:  "Setecientos ochenta y siete",
		788:  "Setecientos ochenta y ocho",
		789:  "Setecientos ochenta y nueve",
		790:  "Setecientos noventa",
		791:  "Setecientos noventa y uno",
		792:  "Setecientos noventa y dos",
		793:  "Setecientos noventa y tres",
		794:  "Setecientos noventa y cuatro",
		795:  "Setecientos noventa y cinco",
		796:  "Setecientos noventa y seis",
		797:  "Setecientos noventa y siete",
		798:  "Setecientos noventa y ocho",
		799:  "Setecientos noventa y nueve",
		800:  "Ochocientos",
		801:  "Ochocientos uno",
		802:  "Ochocientos dos",
		803:  "Ochocientos tres",
		804:  "Ochocientos cuatro",
		805:  "Ochocientos cinco",
		806:  "Ochocientos seis",
		807:  "Ochocientos siete",
		808:  "Ochocientos ocho",
		809:  "Ochocientos nueve",
		810:  "Ochocientos diez",
		811:  "Ochocientos once",
		812:  "Ochocientos doce",
		813:  "Ochocientos trece",
		814:  "Ochocientos catorce",
		815:  "Ochocientos quince",
		816:  "Ochocientos dieciséis",
		817:  "Ochocientos diecisiete",
		818:  "Ochocientos dieciocho",
		819:  "Ochocientos diecinueve",
		820:  "Ochocientos veinte",
		821:  "Ochocientos veintiuno",
		822:  "Ochocientos veintidos",
		823:  "Ochocientos veintitrés",
		824:  "Ochocientos veinticuatro",
		825:  "Ochocientos veinticinco",
		826:  "Ochocientos veintiseis",
		827:  "Ochocientos veintisiete",
		828:  "Ochocientos veintiocho",
		829:  "Ochocientos veintinueve",
		830:  "Ochocientos treinta",
		831:  "Ochocientos treinta y uno",
		832:  "Ochocientos treinta y dos",
		833:  "Ochocientos treinta y tres",
		834:  "Ochocientos treinta y cuatro",
		835:  "Ochocientos treinta y cinco",
		836:  "Ochocientos treinta y seis",
		837:  "Ochocientos treinta y siete",
		838:  "Ochocientos treinta y ocho",
		839:  "Ochocientos treinta y nueve",
		840:  "Ochocientos cuarenta",
		841:  "Ochocientos cuarenta y uno",
		842:  "Ochocientos cuarenta y dos",
		843:  "Ochocientos cuarenta y tres",
		844:  "Ochocientos cuarenta y cuatro",
		845:  "Ochocientos cuarenta y cinco",
		846:  "Ochocientos cuarenta y seis",
		847:  "Ochocientos cuarenta y siete",
		848:  "Ochocientos cuarenta y ocho",
		849:  "Ochocientos cuarenta y nueve",
		850:  "Ochocientos cincuenta",
		851:  "Ochocientos cincuenta y uno",
		852:  "Ochocientos cincuenta y dos",
		853:  "Ochocientos cincuenta y tres",
		854:  "Ochocientos cincuenta y cuatro",
		855:  "Ochocientos cincuenta y cinco",
		856:  "Ochocientos cincuenta y seis",
		857:  "Ochocientos cincuenta y siete",
		858:  "Ochocientos cincuenta y ocho",
		859:  "Ochocientos cincuenta y nueve",
		860:  "Ochocientos sesenta",
		861:  "Ochocientos sesenta y uno",
		862:  "Ochocientos sesenta y dos",
		863:  "Ochocientos sesenta y tres",
		864:  "Ochocientos sesenta y cuatro",
		865:  "Ochocientos sesenta y cinco",
		866:  "Ochocientos sesenta y seis",
		867:  "Ochocientos sesenta y siete",
		868:  "Ochocientos sesenta y ocho",
		869:  "Ochocientos sesenta y nueve",
		870:  "Ochocientos setenta",
		871:  "Ochocientos setenta y uno",
		872:  "Ochocientos setenta y dos",
		873:  "Ochocientos setenta y tres",
		874:  "Ochocientos setenta y cuatro",
		875:  "Ochocientos setenta y cinco",
		876:  "Ochocientos setenta y seis",
		877:  "Ochocientos setenta y siete",
		878:  "Ochocientos setenta y ocho",
		879:  "Ochocientos setenta y nueve",
		880:  "Ochocientos ochenta",
		881:  "Ochocientos ochenta y uno",
		882:  "Ochocientos ochenta y dos",
		883:  "Ochocientos ochenta y tres",
		884:  "Ochocientos ochenta y cuatro",
		885:  "Ochocientos ochenta y cinco",
		886:  "Ochocientos ochenta y seis",
		887:  "Ochocientos ochenta y siete",
		888:  "Ochocientos ochenta y ocho",
		889:  "Ochocientos ochenta y nueve",
		890:  "Ochocientos noventa",
		891:  "Ochocientos noventa y uno",
		892:  "Ochocientos noventa y dos",
		893:  "Ochocientos noventa y tres",
		894:  "Ochocientos noventa y cuatro",
		895:  "Ochocientos noventa y cinco",
		896:  "Ochocientos noventa y seis",
		897:  "Ochocientos noventa y siete",
		898:  "Ochocientos noventa y ocho",
		899:  "Ochocientos noventa y nueve",
		900:  "Novecientos",
		901:  "Novecientos uno",
		902:  "Novecientos dos",
		903:  "Novecientos tres",
		904:  "Novecientos cuatro",
		905:  "Novecientos cinco",
		906:  "Novecientos seis",
		907:  "Novecientos siete",
		908:  "Novecientos ocho",
		909:  "Novecientos nueve",
		910:  "Novecientos diez",
		911:  "Novecientos once",
		912:  "Novecientos doce",
		913:  "Novecientos trece",
		914:  "Novecientos catorce",
		915:  "Novecientos quince",
		916:  "Novecientos dieciséis",
		917:  "Novecientos diecisiete",
		918:  "Novecientos dieciocho",
		919:  "Novecientos diecinueve",
		920:  "Novecientos veinte",
		921:  "Novecientos veintiuno",
		922:  "Novecientos veintidos",
		923:  "Novecientos veintitrés",
		924:  "Novecientos veinticuatro",
		925:  "Novecientos veinticinco",
		926:  "Novecientos veintiseis",
		927:  "Novecientos veintisiete",
		928:  "Novecientos veintiocho",
		929:  "Novecientos veintinueve",
		930:  "Novecientos treinta",
		931:  "Novecientos treinta y uno",
		932:  "Novecientos treinta y dos",
		933:  "Novecientos treinta y tres",
		934:  "Novecientos treinta y cuatro",
		935:  "Novecientos treinta y cinco",
		936:  "Novecientos treinta y seis",
		937:  "Novecientos treinta y siete",
		938:  "Novecientos treinta y ocho",
		939:  "Novecientos treinta y nueve",
		940:  "Novecientos cuarenta",
		941:  "Novecientos cuarenta y uno",
		942:  "Novecientos cuarenta y dos",
		943:  "Novecientos cuarenta y tres",
		944:  "Novecientos cuarenta y cuatro",
		945:  "Novecientos cuarenta y cinco",
		946:  "Novecientos cuarenta y seis",
		947:  "Novecientos cuarenta y siete",
		948:  "Novecientos cuarenta y ocho",
		949:  "Novecientos cuarenta y nueve",
		950:  "Novecientos cincuenta",
		951:  "Novecientos cincuenta y uno",
		952:  "Novecientos cincuenta y dos",
		953:  "Novecientos cincuenta y tres",
		954:  "Novecientos cincuenta y cuatro",
		955:  "Novecientos cincuenta y cinco",
		956:  "Novecientos cincuenta y seis",
		957:  "Novecientos cincuenta y siete",
		958:  "Novecientos cincuenta y ocho",
		959:  "Novecientos cincuenta y nueve",
		960:  "Novecientos sesenta",
		961:  "Novecientos sesenta y uno",
		962:  "Novecientos sesenta y dos",
		963:  "Novecientos sesenta y tres",
		964:  "Novecientos sesenta y cuatro",
		965:  "Novecientos sesenta y cinco",
		966:  "Novecientos sesenta y seis",
		967:  "Novecientos sesenta y siete",
		968:  "Novecientos sesenta y ocho",
		969:  "Novecientos sesenta y nueve",
		970:  "Novecientos setenta",
		971:  "Novecientos setenta y uno",
		972:  "Novecientos setenta y dos",
		973:  "Novecientos setenta y tres",
		974:  "Novecientos setenta y cuatro",
		975:  "Novecientos setenta y cinco",
		976:  "Novecientos setenta y seis",
		977:  "Novecientos setenta y siete",
		978:  "Novecientos setenta y ocho",
		979:  "Novecientos setenta y nueve",
		980:  "Novecientos ochenta",
		981:  "Novecientos ochenta y uno",
		982:  "Novecientos ochenta y dos",
		983:  "Novecientos ochenta y tres",
		984:  "Novecientos ochenta y cuatro",
		985:  "Novecientos ochenta y cinco",
		986:  "Novecientos ochenta y seis",
		987:  "Novecientos ochenta y siete",
		988:  "Novecientos ochenta y ocho",
		989:  "Novecientos ochenta y nueve",
		990:  "Novecientos noventa",
		991:  "Novecientos noventa y uno",
		992:  "Novecientos noventa y dos",
		993:  "Novecientos noventa y tres",
		994:  "Novecientos noventa y cuatro",
		995:  "Novecientos noventa y cinco",
		996:  "Novecientos noventa y seis",
		997:  "Novecientos noventa y siete",
		998:  "Novecientos noventa y ocho",
		999:  "Novecientos noventa y nueve",
		1000: "Mil",
	}
)

func TestText2NumES(t *testing.T) {

}
